language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - sudo gem install cocoapods-keys
install:
  - pod keys set MANDRILL_API "-"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace SwiftMandrill.xcworkspace -scheme "SwiftMandrill" -destination "OS=9.2,name=iPhone 6s Plus" | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
